# Démarrer le serveur de développement  
runserver:  
	python manage.py runserver  

# Effectuer les migrations  
migrate:  
	python manage.py migrate  

# Créer une migration pour les modifications de modèles  
makemigrations:  
	python manage.py makemigrations  

# Lancer les tests  
test:  
	python manage.py test  

# Nettoyer les fichiers compilés  
clean:  
	find . -name "*.pyc" -exec rm -f {} \;   
	find . -name "__pycache__" -exec rm -rf {} \;
# Ouvrir shell  
shell:  
	python manage.py shell   
#  Creer admin user
createsuperuser:  
	python manage.py createsuperuser